#<tag> : <report_filename>

ISO_STRATCONTROL_GLITCH:
  NORMAL:
    REPORT: ISO_STRATCONTROL_GLITCH_NORMAL.rpt
    PROOF : ISO_STRATCONTROL_GLITCH_NORMAL_PROOFS.rpt
RET_CONTROL_GLITCH :
  SAVE:
    REPORT: RET_CONTROL_GLITCH_SAVE.rpt
    PROOF : RET_CONTROL_GLITCH_SAVE_PROOFS.rpt
#ISO_STRATEGY_REDUND :
#  HETERO :
#    REPORT : ISO_STRATEGY_REDUND_HETERO.rpt
#    PROOF : ISO_STRATEGY_REDUND_HETERO_PROOFS.rpt
#  REAL_PATH :
#    REPORT : ISO_STRATEGY_REDUND_FEED_REAL_PATHS.rpt
#    PROOF : ISO_STRATEGY_REDUND_FEED_PATHS_PROOFS.rpt
#    DESIGN_FEED_THROUG_REPORT : ISO_STRATEGY_REDUND_DESIGN_FEED_THROUGH.rpt
#
#  FEED_PATH :
#    REPORT : ISO_STRATEGY_REDUND_FEED_REAL_PATHS.rpt
#    PROOF : ISO_STRATEGY_REDUND_REAL_PATHS_PROOFS.rpt
#    DESIGN_FEED_THROUG_REPORT : ISO_STRATEGY_REDUND_DESIGN_FEED_THROUGH.rpt
